import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "public/**.js", //The files generated for the PWA are here and are not typed
    ".agents/**", //The files generated by the AI are here and are not typed
    "scripts/**", //The files generated by the AI are here and are not typed
  ]),
]);

export default eslintConfig;
