name: Notebooks Cleanup Cron

on:
  schedule:
    # Runs at 00:00 on the 1st day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Assets Cleanup API
        env:
          APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$APP_URL" ]; then
            echo "Error: NEXT_PUBLIC_APP_URL variable is not set."
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "Error: CRON_SECRET secret is not set."
            exit 1
          fi
          curl -f -X POST "$APP_URL/api/cron/notebook-assets" \
          -H "Authorization: Bearer $CRON_SECRET" \
          -H "Content-Type: application/json"

      - name: Trigger Notebooks DB Cleanup API
        env:
          APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$APP_URL" ]; then
            echo "Error: NEXT_PUBLIC_APP_URL variable is not set."
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "Error: CRON_SECRET secret is not set."
            exit 1
          fi
          curl -f -X POST "$APP_URL/api/cron/cleanup-notebooks" \
          -H "Authorization: Bearer $CRON_SECRET" \
          -H "Content-Type: application/json"
