import { User } from "../user.schema";

/**
 * Creates a mock User object with all required fields for testing.
 */
export const createMockUser = (overrides: Partial<User> = {}): User => {
  return {
    id: "test-user-id",
    email: "test@example.com",
    name: "Test User",
    role: "student",
    photoUrl: null,
    googleLinked: false,
    locale: "pt",
    isActive: true,
    onboarded: true,
    onboardingStep: 1,
    cellphone: null,
    taxId: null,
    businessTaxId: null,
    pixKey: null,
    pixType: null,
    classesStartDate: null,
    languages: [],
    abacatePayCustomerId: null,
    assignedPlanId: null,
    dueDay: 10,
    nickname: null,
    birthDate: null,
    nationality: null,
    address: null,
    guardianName: null,
    guardianTaxId: null,
    guardianRelationship: null,
    lastLoginAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    lastPlacementTestDate: null,
    currentEloScore: 600,
    currentXP: 0,
    streakCount: 0,
    lastPracticeDate: null,
    pushNotificationsEnabled: true,
    appNotificationsEnabled: true,
    notificationPrefs: {
      streak: true,
      roadmap: true,
      classes: true,
      marketing: false,
    },
    teacherHourlyRate: 4200,
    mfaEnabled: false,
    mfaSecret: null,
    cancellationPending: false,
    cancellationPixCode: null,
    cancellationPixImage: null,
    cancellationAmount: null,
    ...overrides,
  } as User;
};
